#!/bin/bash

# Nihesh Anderson - knandy

# createws - Create Workspace | This script installs all the required applications used by knandy

# Tmux for command line and create alias to open session 0
sudo apt-get install tmux
echo "alias tmux0='tmux attach -t 0'" >> ~/.bashrc

# Sublime text-3
sudo add-apt-repository ppa:webupd8team/sublime-text-3
sudo apt-get update
sudo apt-get install sublime-text-installer

# SSH client
sudo apt-get install ssh




