#!/bin/bash

# assumes 16 bit network address, pings 256 addresses corresponding to $1(3rd byte) and filters out active connections
# pinglan 32 searches for all active hosts in 192.168.32.*

nmap -sP 192.168.$1.1/24

